export interface IconCatalogEntry {
  icon: string
  name: string
  category: string
}

export const iconCatalog: IconCatalogEntry[] = [
  { icon: '+', name: 'add', category: 'Actions' },
  { icon: '−', name: 'remove', category: 'Actions' },
  { icon: '×', name: 'close', category: 'Actions' },
  { icon: '✓', name: 'check', category: 'Actions' },
  { icon: '✎', name: 'edit', category: 'Actions' },
  { icon: '↻', name: 'refresh', category: 'Actions' },
  { icon: '↶', name: 'undo', category: 'Actions' },
  { icon: '↷', name: 'redo', category: 'Actions' },
  { icon: '⇧', name: 'upload', category: 'Actions' },
  { icon: '⇩', name: 'download', category: 'Actions' },
  { icon: '↩', name: 'return', category: 'Actions' },
  { icon: '↵', name: 'enter', category: 'Actions' },

  { icon: '⌂', name: 'home', category: 'Navigation' },
  { icon: '☰', name: 'menu', category: 'Navigation' },
  { icon: '↑', name: 'arrow up', category: 'Navigation' },
  { icon: '↓', name: 'arrow down', category: 'Navigation' },
  { icon: '←', name: 'arrow left', category: 'Navigation' },
  { icon: '→', name: 'arrow right', category: 'Navigation' },
  { icon: '‹', name: 'chevron left', category: 'Navigation' },
  { icon: '›', name: 'chevron right', category: 'Navigation' },
  { icon: '⌃', name: 'chevron up', category: 'Navigation' },
  { icon: '⌄', name: 'chevron down', category: 'Navigation' },
  { icon: '«', name: 'first', category: 'Navigation' },
  { icon: '»', name: 'last', category: 'Navigation' },
  { icon: '⤢', name: 'expand', category: 'Navigation' },
  { icon: '⋯', name: 'more horizontal', category: 'Navigation' },
  { icon: '⋮', name: 'more vertical', category: 'Navigation' },

  { icon: 'ⓘ', name: 'information', category: 'Status' },
  { icon: '?', name: 'question', category: 'Status' },
  { icon: '⚠︎', name: 'warning', category: 'Status' },
  { icon: '⊗', name: 'error', category: 'Status' },
  { icon: '⊘', name: 'prohibited', category: 'Status' },
  { icon: '◉', name: 'selected', category: 'Status' },
  { icon: '○', name: 'unselected', category: 'Status' },
  { icon: '◷', name: 'pending', category: 'Status' },
  { icon: '☆', name: 'star outline', category: 'Status' },
  { icon: '★', name: 'star filled', category: 'Status' },
  { icon: '♡', name: 'heart outline', category: 'Status' },
  { icon: '♥', name: 'heart filled', category: 'Status' },

  { icon: '▶︎', name: 'play', category: 'Media' },
  { icon: 'Ⅱ', name: 'pause', category: 'Media' },
  { icon: '■', name: 'stop', category: 'Media' },
  { icon: '●', name: 'record', category: 'Media' },
  { icon: '◀︎', name: 'previous', category: 'Media' },
  { icon: '▶︎', name: 'next', category: 'Media' },
  { icon: '◀◀', name: 'rewind', category: 'Media' },
  { icon: '▶▶', name: 'fast forward', category: 'Media' },
  { icon: '⏏︎', name: 'eject', category: 'Media' },
  { icon: '♪', name: 'music', category: 'Media' },

  { icon: '□', name: 'window', category: 'Layout' },
  { icon: '❐', name: 'restore window', category: 'Layout' },
  { icon: '◧', name: 'panel left', category: 'Layout' },
  { icon: '◨', name: 'panel right', category: 'Layout' },
  { icon: '▥', name: 'columns', category: 'Layout' },
  { icon: '▦', name: 'grid', category: 'Layout' },
  { icon: '≡', name: 'list', category: 'Layout' },
  { icon: '⊢', name: 'tree branch', category: 'Layout' },
  { icon: '⊟', name: 'collapse', category: 'Layout' },
  { icon: '⊞', name: 'expand node', category: 'Layout' },

  { icon: '⇅', name: 'sort', category: 'Data' },
  { icon: '⇡', name: 'sort ascending', category: 'Data' },
  { icon: '⇣', name: 'sort descending', category: 'Data' },
  { icon: '∑', name: 'sum', category: 'Data' },
  { icon: '∞', name: 'infinity', category: 'Data' },
  { icon: '%', name: 'percent', category: 'Data' },
  { icon: '=', name: 'equal', category: 'Data' },
  { icon: '≠', name: 'not equal', category: 'Data' },
  { icon: '≥', name: 'greater or equal', category: 'Data' },
  { icon: '≤', name: 'less or equal', category: 'Data' },
  { icon: 'ƒ', name: 'function', category: 'Data' },

  { icon: '⚙︎', name: 'settings', category: 'System' },
  { icon: '⌕', name: 'search', category: 'System' },
  { icon: '⎙', name: 'print', category: 'System' },
  { icon: '⌨︎', name: 'keyboard', category: 'System' },
  { icon: '⌘', name: 'command', category: 'System' },
  { icon: '⌥', name: 'option', category: 'System' },
  { icon: '⏻', name: 'power', category: 'System' },
  { icon: '✉︎', name: 'mail', category: 'System' },
  { icon: '☎︎', name: 'phone', category: 'System' },

  { icon: '¶', name: 'paragraph', category: 'Text' },
  { icon: '§', name: 'section', category: 'Text' },
  { icon: '•', name: 'bullet', category: 'Text' },
  { icon: '…', name: 'ellipsis', category: 'Text' },
  { icon: '❝', name: 'quote', category: 'Text' },
  { icon: '⇥', name: 'indent', category: 'Text' },
  { icon: '⇤', name: 'outdent', category: 'Text' },
  { icon: '©', name: 'copyright', category: 'Text' },
  { icon: '®', name: 'registered', category: 'Text' },
  { icon: '™', name: 'trademark', category: 'Text' },
]
